language: php

php:
  - 5.6
  - hhvm

jobs:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer require satooshi/php-coveralls --dev

script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
